### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/?profile_type=company
Content-Type: application/json

{
  "username": "userRanom123",
  "email": "random.useыr@example.com",
  "password": "SecurePass456!",
  "role": "ADMIN",
  "company": {
    "name": "ООО \"Рога и Копыта\"",
    "inn": "7707983893",
    "ogrn": "1027710132195",
    "bic": "074525225",
    "correspondentAccount": "43274832",
    "registrationDate": "2022-06-15"
  }
}

### Метод для регистрации физ лица
POST http://localhost:8080/api/v1/auth/register/?profile_type=individual
Content-Type: application/json

{
  "username": "usersRandom123",
  "email": "random.user1@example.com",
  "password": "SecurePass456!",
  "phoneNumber": "+7 (999) 123-45-67",
  "role": "CARRIER",
  "individual": {
    "fullname": "Иван Иванов",
    "passportNum": 123456,
    "passportSeries": 7890,
    "whoGive": "УФМС России по г. Москве",
    "departmentCode": "770-001",
    "photos": [
      {
        "guid": "4b4d77cf-6b0d-4d82-adc8-9323419a9f68"
      },
      {
        "guid": "031172a0-3ab8-4ed1-9136-5df937bc16f6"
      }
    ]
  }
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "random.useыr@example.com",
  "password": "SecurePass456!"
}

### Метод для обновления токена доступа
POST http://localhost:8080/api/v1/auth/refresh-token/
Set-Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyUmFub20xMjMiLCJpYXQiOjE3Mzg3MDM5MzEsImV4cCI6MTczODc5MDMzMX0.02pavYB_CFvh6cVFe645udbLza2pFAgPspNzY_B4Jng; Max-Age=604800; Expires=Tue, 11 Feb 2025 20:58:01 GMT; Path=/; HttpOnly

