### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "userRanom123",
  "email": "papasagid@gmail.com",
  "password": "SecurePass456!",
  "legalTypeDto": "INDIVIDUAL",
  "role": "ADMIN"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "papasagid@gmail.com",
  "password": "SecurePass456!"
}

### Метод для обновления токена доступа
POST http://localhost:8080/api/v1/auth/refresh-token/
Set-Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyUmFub20xMjMiLCJpYXQiOjE3NDIyMzQ1MzksImV4cCI6MTc0MjgzOTMzOX0.Qbp9CGduDXFfzvCWkEqySFbVS8hGKZhVe6nrE_pIemE; Max-Age=604800; Expires=Mon, 24 Mar 2025 18:02:19 GMT; Path=/; HttpOnly

### Метод для сбора пароля
POST http://localhost:8080/api/v1/auth/password-recovery/
Content-Type: application/json

{
  "email": "papasagid@gmail.com"
}

### Метод для установки нового пароля
POST http://localhost:8080/api/v1/auth/reset-password/?token=-TRYAwZaoINbJlUj0cZgvI56PJwbkK-HRZq5FdzsYg0
Content-Type: application/json

{
  "newPassword": "k.,k.linux"
}

### Метод для выхода из системы
POST http://localhost:8080/api/v1/auth/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2zQstCyadCwayIsImlhdCI6MTczODU2NDc3NywiZXhwIjoxNzM4NjUxMTc3fQ.az8loA4IKC4rjWviK3AsycyH3-Awubnd4iqmVUiyZfA


