@driverUrl=http://localhost:8080/api/v1/drivers

### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "sagid123",
  "email": "sagid@mail.com",
  "password": "SecurePass456!",
  "legalType": "INDIVIDUAL",
  "role": "CARRIER"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "sagid@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Set-Cookie"));
%}

### Идентификатор изображения
@driver_image_1=0b594908-c8fe-4c9b-8af9-900d406027ae

### Метод для создания записи о [водителе]
POST {{driverUrl}}//
Cookie: {{access_token}}
Content-Type: application/json

{
  "fullName": "Михаил Петрович",
  "licenseCategory": "B",
  "licenseNumber": "0127 445115",
  "issueDate": "2023-04-30",
  "expirationDate": "2033-04-30",
  "imagesIds": [
    "{{driver_image_1}}"
  ]
}

### Метод для получения всех записей о водителях профиля с пагинацией
GET {{driverUrl}}//?pageNumber=1&pageSize=5
Cookie: {{access_token}}

### Метод для получения всех записей о водителях профиля [СПИСОК БЕЗ ПАГИНАЦИИ]
GET {{driverUrl}}/list/
Cookie: {{access_token}}

###
@driverId=3d6e80b7-1ebd-46aa-897c-347330b4f54e

### Метод для получения данных записи водителя по id
GET {{driverUrl}}/{{driverId}}/
Cookie: {{access_token}}

### Метод для обновления данных записи водителя по id
PATCH {{driverUrl}}/{{driverId}}/
Cookie: {{access_token}}
Content-Type: application/json

{
  "fullName": "Михаил ",
  "licenseCategory": "C",
  "licenseNumber": "0503 445115",
  "issueDate": "2023-04-30",
  "expirationDate": "2033-04-30",
  "imagesIds": [
    "{{driver_image_1}}"
  ]
}

### Метод для удаление записи о водителя по id
DELETE {{driverUrl}}/{{driverId}}/
Cookie: {{access_token}}
