### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "ann.ten.tkdlove@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}


### Метод для получения данных о профиле
GET http://localhost:8080/api/v1/profile/
Authorization: Bearer {{access_token}}