### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "annten1@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Set-Cookie"));
%}

### Метод для получения данных о профиле
GET http://localhost:8080/api/v1/profile/
Set-Cookie: {{access_token}}

### Идентификатор профиля другого пользователя
@foreignProfileId=

### Метод для получения профиля другого пользователя по ID
GET http://localhost:8080/api/v1/profile/{{foreignProfileId}}/
Set-Cookie: access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2xpazEiLCJpYXQiOjE3NTAwODQ0MjAsImV4cCI6MTc1MDA5MzA2MH0.v4JKIsebkdRvVI-YMfNhbYmRsX1TCLLAnoL7Q_l0udQ; Max-Age=60480000; Expires=Mon, 17 May 2027 14:33:40 GMT; Path=/; HttpOnly
Set-Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2xpazEiLCJpYXQiOjE3NTAwODQ0MjAsImV4cCI6MTc1MDE0NDkwMH0.VGTa9taYN4OmwM-aoI2bXRGJDkPp9D3M9qU2ArU5m5M; Max-Age=60480000; Expires=Mon, 17 May 2027 14:33:40 GMT; Path=/; HttpOnly

### Идентификатор изображений пасспорта
@imageId_1=a57bf467-0bfa-44b2-bb66-c3e6bc139c18
@imageId_2=cc65d8bc-2438-44e8-8ff4-7620adc18203

### Метод для обновления данных профиля
PATCH http://localhost:8080/api/v1/profile/
Set-Cookie: {{access_token}}
Content-Type: application/json

{
  "contactData": {
    "telegramLink": "user@example.com",
    "whatsappLink": "+1234567890",
    "phoneNumber": "123 Main Street, City, Country"
  },
  "individual": {
    "fullName": "Micha Иванов",
    "passportNumber": "1235 567890",
    "issuedBy": "УФМС России по г. Москве",
    "issueDate": "2020-01-15",
    "departmentCode": "770-001",
    "registrationAddress": "г. Москва, ул. Ленина, д. 10",
    "imagesIds": [
      "{{imageId_1}}",
      "{{imageId_2}}"
    ]
  }
}

###
#{
#  "contactData": {
#    "telegramLink": "user@ example.com",
#    "whatsappLink": "+1234567890",
#    "phoneNumber": "123 Main Street, City, Country"
#  },
#  "company": {
#    "name": "Example Corp",
#    "inn": "1234567890",
#    "ogrn": "1122334455667",
#    "bic": "044525225"
#  }
}