@baseUrl = http://localhost:8080/api/v1/transports

### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "sagid123",
  "email": "sagid@mail.com",
  "password": "SecurePass456!",
  "legalType": "INDIVIDUAL",
  "role": "CARRIER"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "sagid@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Set-Cookie"));
%}

###
@driverId=3d6e80b7-1ebd-46aa-897c-347330b4f54e
@trailerId=5a9aecb5-abe0-4a78-b587-1f638ac1dcad
@transport_image_1=0b594908-c8fe-4c9b-8af9-900d406027ae

### Метод для создания транспорта
POST {{baseUrl}}//
Cookie: {{access_token}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "brand": "Volvo",
  "model": "FH16",
  "manufactureYear": 2020,
  "transportNumber": "A123BC",
  "embeddedTrailerDetails": {
    "liftingCapacity": 10000,
    "bodyType": "Тент",
    "loadType": "Верхняя",
    "unloadType": "Задняя",
    "length": 10,
    "width": 3,
    "height": 3,
    "volume": 30
  },
  "trailersIds": [
    "{{trailerId}}"
  ],
  "imagesIds": [
    "{{transport_image_1}}"
  ]
}

### Получение деталей транспортов с пагинацией
GET {{baseUrl}}//?pageNumber=1&pageSize=5
Cookie: {{access_token}}

###
@transportId=838a2564-f08b-4de5-b63e-b2bf3e4a9124

### Получение деталей транспорта
GET {{baseUrl}}/{{transportId}}/
Cookie: {{access_token}}
Content-Type: application/json

### Обновление деталей транспорта
PATCH {{baseUrl}}/{{transportId}}/
Cookie: {{access_token}}
Content-Type: application/json

{
    "brand": "Volvo",
    "model": "FH16",
    "manufactureYear": 2024,
    "transportNumber": "A123BC",
    "embeddedTrailerDetails": {
        "liftingCapacity": 10000,
        "bodyType": "Тент",
        "loadType": "Верхняя",
        "unloadType": "Задняя",
        "length": 10,
        "width": 3,
        "height": 3,
        "volume": 30
    },
    "trailersIds": [
        "{{trailerId}}"
    ],
    "imagesIds": [
      "{{transport_image_1}}"
    ]
}

### Удаление транспорта
DELETE {{baseUrl}}/{{transportId}}/
Cookie: {{access_token}}