version: '3.9'
services:
#  cargo-way-app:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - cargo-way-postgres

  cargo-way-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - "${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

#  minio:
#    build:
#      dockerfile: docker/minio/Dockerfile
#    container_name: minio
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
#      MINIO_API_PORT: ${MINIO_API_PORT}
#      MINIO_WEBUI_PORT: ${MINIO_WEBUI_PORT}
#    volumes:
#      - "${MINIO_VOLUME_PATH}:/data"
#    ports:
#      - "${MINIO_API_PORT}:9000"
#      - "${MINIO_WEBUI_PORT}:9090"

volumes:
  pg_data: