spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

minio:
  endpoint: ${MINIO_HOST}:${MINIO_API_PORT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: ${MINIO_BUCKET_NAME}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION}
