@transportUrl=http://localhost:8080/api/v1/transports
@cargoUrl=http://localhost:8080/api/v1/cargos
@driverUrl=http://localhost:8080/api/v1/drivers
@trailersUrl=http://localhost:8080/api/v1/trailers

### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "sagid123",
  "email": "sagid@mail.com",
  "password": "SecurePass456!",
  "legalType": "INDIVIDUAL",
  "role": "CARRIER"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "sagid@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Метод для создания записи о [водителе]
POST {{driverUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "fullName": "Алексей Яковлев",
  "licenseCategory": "A",
  "licenseNumber": "0319 445115",
  "issueDate": "2023-04-30",
  "expirationDate": "2033-04-30"
}

###
@driverId=32dad756-cdde-4105-9f4f-c62f164fd81f

### Метод для создания записи о [прицепе]
POST {{trailersUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Мерседес Бенц",
  "trailerNumber": "A123BC",
  "liftingCapacity": 10000,
  "bodyType": "Тент",
  "loadType": "Верхняя",
  "unloadType": "Задняя",
  "length": 10,
  "width": 3,
  "height": 3,
  "volume": 30
}

###
@trailerId=d3411083-654f-47e9-b58f-445da1d50dff

### Метод для создания записи о транспорте
POST {{transportUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "brand": "Volvo",
  "model": "FH16",
  "manufactureYear": 2020,
  "transportNumber": "A123BC",

  "trailersIds": [
    "{{trailerId}}"
  ]
}

### Метод для получения записи о транспортах
GET {{transportUrl}}//?pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
@transport_id=1b5d3d28-7a02-4a0b-9965-7f5788f5e50f

### Запрос на получение списка записей грузов
POST {{cargoUrl}}/search/?pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "priceTo": 5000000.00
}

###
@cargo_order_id=807df26e-9d4a-487e-b522-268b2236df72

### Создать отклик от перевозчика на груз
POST {{cargoUrl}}/{{cargo_order_id}}/transport/{{transport_id}}/response/
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Идентификатор отклика [МОЖНО ПОСМОТРЕТЬ ДЕТАЛИ ГРУЗА]
@response_id=

### Отменить отклик от перевозчкаи на груз
POST {{cargoUrl}}/{{cargo_order_id}}/response/{{response_id}}/cancel/
Authorization: Bearer {{access_token}}
Content-Type: application/json
