@transportUrl=http://localhost:8080/api/v1/transports
@cargoUrl=http://localhost:8080/api/v1/cargos
@driverUrl=http://localhost:8080/api/v1/drivers
@trailersUrl=http://localhost:8080/api/v1/trailers

### Метод для регистрации компании
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "sagid123",
  "email": "sagid@mail.com",
  "password": "SecurePass456!",
  "legalType": "INDIVIDUAL",
  "role": "CARRIER"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "sagid@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Метод для создания записи о [водителе]
POST {{driverUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "fullName": "Алексей Яковлев",
  "licenseCategory": "A",
  "licenseNumber": "0319 445115",
  "issueDate": "2023-04-30",
  "expirationDate": "2033-04-30"
}

###
@driverId=29ea4d4c-1258-4948-8852-484903c70f8e

### Метод для создания записи о [прицепе]
POST {{trailersUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Мерседес Бенц",
  "trailerNumber": "АВ1234",
  "liftingCapacity": 10000,
  "bodyType": "Тент",
  "loadType": "Верхняя",
  "unloadType": "Задняя",
  "length": 10,
  "width": 3,
  "height": 3,
  "volume": 30
}

###
@trailerId=b4e78f10-dcb9-4e73-9128-6cf83b3ec068

### Метод для создания записи о транспорте
POST {{transportUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "brand": "Volvo",
  "model": "FH16",
  "manufactureYear": 2020,
  "transportNumber": "A123BC",

  "trailersIds": [
    "{{trailerId}}"
  ]
}

### Метод для получения записи о транспортах
GET {{transportUrl}}//?pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
@transport_id=cbf1cdeb-e34d-4e50-9e35-d56e2686f409

### Запрос на получение списка записей грузов
POST {{cargoUrl}}/search/?pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "priceTo": 5000000.00
}

###
@cargo_order_id=8a202fe9-96b3-4ac5-b715-2de0bba4b310

### Создать отклик от перевозчика на груз
POST {{cargoUrl}}/{{cargo_order_id}}/transport/{{transport_id}}/response/
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Идентификатор отклика [МОЖНО ПОСМОТРЕТЬ ДЕТАЛИ ГРУЗА]
@response_id=a14afe80-2ef3-4d06-a6fc-aa62ec055deb

### Отменить отклик от перевозчкаи на груз
POST {{cargoUrl}}/{{cargo_order_id}}/response/{{response_id}}/cancel/
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Просмотреть список записей перевозчика [ACTIVE, WAITING, HISTORY]
GET {{cargoUrl}}/carrier/general/?cargoCategory=WAITING&pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Content-Type: application/json
