@transportUrl=http://localhost:8080/api/v1/transports
@cargoUrl=http://localhost:8080/api/v1/cargos
@driverUrl=http://localhost:8080/api/v1/drivers
@trailersUrl=http://localhost:8080/api/v1/trailers

### Метод для регистрации компании [ЗАКАЗЧИК + ФИЗ ЛИЦО]
POST http://localhost:8080/api/v1/auth/register/
Content-Type: application/json

{
  "username": "lolik1",
  "email": "annten1@mail.com",
  "password": "SecurePass456!",
  "legalType": "INDIVIDUAL",
  "role": "CUSTOMER"
}

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "annten1@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Метод для создания груза
POST {{cargoUrl}}//
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "машина",
  "description": " машина для гонок",
  "weight": 1200,
  "volume": 90,
  "loadType": "Задняя",
  "unloadType": "Задняя",
  "bodyType": "Тент",
  "dimensions": {
    "length": 120,
    "width": 50,
    "height": 20
  },
  "route": {
    "from": "New York",
    "to": "Los Angeles"
  },
  "price": 5000000,
  "typePay": "НДС",
  "readyDate": "2025-05-22",
  "deliveryDate": "2025-06-01"
}

### Получение списка груза [INTERNAL]
GET {{cargoUrl}}/general/?cargoCategory=EXTERNAL&pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Accept: application/json

### [ЭТОТ ID НАДО ПЕРЕДАТЬ В СЦЕНАРИЙ В ФАЙЛЕ carrier]
@cargo_order_id=e76f65d2-2b9b-4e5b-b8ec-edc57025da74

### Получение деталей груза
GET {{cargoUrl}}/{{cargo_order_id}}/
Authorization: Bearer {{access_token}}
Accept: application/json

### Публикация записи [после ПЕРЕЙТИ В ФАЙЛ carrier И ОТКЛИКНУТЬСЯ НА ЗАКАЗ ПО ID]
PATCH {{cargoUrl}}/{{cargo_order_id}}/publish/
Authorization: Bearer {{access_token}}
Accept: application/json

### Снятие записи с публикации
PATCH {{cargoUrl}}/{{cargo_order_id}}/draft/
Authorization: Bearer {{access_token}}
Accept: application/json

### Обновление записи о грузе [ПРОВЕРКА О НЕВОЗМОЖНОСТИ ОБНОВЛЕНИЯ]
PATCH {{cargoUrl}}/{{cargo_order_id}}/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Box",
  "description": "Большая коробка",
  "weight": 10,
  "volume": 1000,
  "loadType": "Задняя",
  "unloadType": "Задняя",
  "bodyType": "Тент",
  "dimensions": {
    "length": 10,
    "width": 5,
    "height": 20
  },
  "route": {
    "from": "New York",
    "to": "Los Angeles"
  },
  "price": 10000,
  "typePay": "НДС",
  "readyDate": "2025-05-22",
  "deliveryDate": "2025-06-01"
}

### Получение списка груза [EXTERNAL]
GET {{cargoUrl}}/general/?cargoCategory=EXTERNAL&pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Accept: application/json

### Идентификатор запроса, который выбрали
@response_id=d0ef6b06-1d11-4de1-8ea3-2f67c174e514

### Выбор перевозчика и начало исполнения заказа
POST {{cargoUrl}}/{{cargo_order_id}}/response/{{response_id}}/accept/
Authorization: Bearer {{access_token}}
Accept: application/json

### Отмена исполнения заказа
POST {{cargoUrl}}/{{cargo_order_id}}/cancel/
Authorization: Bearer {{access_token}}
Accept: application/json

### Подтвердить запрос на завершение исполнения заказа
POST {{cargoUrl}}/{{cargo_order_id}}/endExecution/confirm/
Authorization: Bearer {{access_token}}
Accept: application/json